last_project: D:/project/project/Assets/ConfigAsset/ShareJsonConfig/1.json
node_type:
  Action: {}
  Composite: {}
  Condition: {}
  Decorator: {}
  Root: {}
nodes:
  AimAtTargetPoint:
    des: "\u5411\u76EE\u6807\u7784\u51C6"
    params: {}
    type: Action
  FindPath:
    des: "\u5BFB\u8DEF"
    params: {}
    type: Action
  FindPatrolSpot:
    params: {}
    type: Action
  Idle:
    des: "\u53D1\u5446"
    params:
      delay:
        des: "\u79D2"
        type: float
    type: Action
  Invert:
    params: {}
    type: Decorator
  PurchaseMainWeapon:
    params: {}
    type: Action
  RandomSelector:
    params: {}
    type: Composite
  RandomSequence:
    params: {}
    type: Composite
  Root:
    params: {}
    type: Root
  Selector:
    params: {}
    type: Composite
  Sequence:
    params: {}
    type: Composite
  StartFire:
    des: "\u5F00\u67AA"
    params: {}
    type: Action
  SwitchWeapon:
    params: {}
    type: Action
  TurnAroundToTarget:
    params: {}
    type: Action
