last_project: D:/project/ds/Assets/StreamingAssets/ConfigAsset/ShareJsonConfig/2.json
node_type:
  Action: {}
  Composite: {}
  Condition: {}
  Decorator: {}
  Root: {}
nodes:
  AimAtTargetPoint:
    des: "\u5411\u76EE\u6807\u7784\u51C6"
    params: {}
    type: Action
  AttackOpponentSelected:
    des: "\u53D1\u73B0\u9501\u5B9A\u654C\u4EBA"
    params: {}
    type: Condition
  BombDeployed:
    des: "C4\u5DF2\u90E8\u7F72"
    params: {}
    type: Condition
  Crouch:
    des: "\u8E72\u4E0B"
    params: {}
    type: Action
  DefuseC4Bomb:
    des: "\u62C6\u5F39"
    params: {}
    type: Action
  EnemyInSight:
    des: "\u654C\u4EBA\u5728\u89C6\u91CE\u5185"
    params: {}
    type: Condition
  ExistC4Projectile:
    des: "\u5B58\u5728C4\u6389\u843D"
    params: {}
    type: Condition
  FindC4Spot:
    des: "\u5BFB\u8DEF\u5230C4"
    params: {}
    type: Action
  FindCloseEnemySpot:
    des: "\u627E\u5230\u6700\u8FD1\u7684\u654C\u4EBA"
    params: {}
    type: Action
  FindDefenceSpot:
    des: "\u5BFB\u8DEF\u5230\u9632\u5B88\u70B9"
    params: {}
    type: Action
  FindPath:
    des: "\u5BFB\u8DEF"
    params: {}
    type: Action
  FindPatrolSpot:
    params: {}
    type: Action
  FindRetreatSpot:
    des: "\u5BFB\u8DEF\u5230\u64A4\u9000\u70B9"
    params: {}
    type: Action
  HasC4:
    des: "\u8EAB\u4E0A\u6709C4"
    params: {}
    type: Condition
  Idle:
    des: "\u53D1\u5446"
    params:
      delay:
        des: "\u79D2"
        type: float
    type: Action
  InBombArea:
    des: "\u5728\u70B8\u5F39\u533A\u57DF"
    params: {}
    type: Condition
  Invert:
    params: {}
    type: Decorator
  IsCT:
    des: "\u662F\u8B66"
    params: {}
    type: Condition
  IsT:
    des: "\u662F\u532A"
    params: {}
    type: Condition
  MatchInProgress:
    des: "\u6218\u6597\u8FDB\u884C\u4E2D"
    params: {}
    type: Condition
  MoveToC4DeployArea:
    des: "\u79FB\u52A8\u5230\u90E8\u7F72\u7684\u70B8\u5F39\u70B9"
    params: {}
    type: Action
  MoveToC4Projectile:
    des: "\u79FB\u52A8\u5230C4\u6389\u843D"
    params: {}
    type: Action
  MoveToC4Spot:
    des: "\u79FB\u52A8\u5230\u4E0B\u5305\u70B9"
    params: {}
    type: Action
  MoveToCloseEnemy:
    des: "\u79FB\u52A8\u5230\u6700\u8FD1\u654C\u4EBA"
    params: {}
    type: Action
  Patrol:
    des: "\u5DE1\u903B"
    params: {}
    type: Action
  PickUpC4Bomb:
    des: "\u62FE\u53D6C4"
    params: {}
    type: Action
  PurchaseMainWeapon:
    params: {}
    type: Action
  RandomSelector:
    params: {}
    type: Composite
  RandomSequence:
    params: {}
    type: Composite
  ReloadWeapon:
    des: "\u88C5\u5F39"
    params: {}
    type: Action
  Repeat:
    params:
      times:
        des: ''
        type: int
    type: Decorator
  Root:
    params: {}
    type: Root
  SelectWeapon:
    des: "\u9009\u62E9\u6B66\u5668"
    params: {}
    type: Action
  Selector:
    params: {}
    type: Composite
  Sequence:
    params: {}
    type: Composite
  SpawnC4:
    des: "\u4E0B\u5305"
    params: {}
    type: Action
  StartFire:
    des: "\u5F00\u67AA"
    params: {}
    type: Action
  SwitchMelee:
    des: "\u5207\u6362\u5230\u8FD1\u6218\u6B66\u5668"
    params: {}
    type: Action
  SwitchWeapon:
    params: {}
    type: Action
  TurnAroundToTarget:
    params: {}
    type: Action
  UtilFail:
    params: {}
    type: Decorator
  UtilSuccess:
    params: {}
    type: Decorator
